parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    # configure these for your database server
    driver: 'pdo_pgsql'
    server_version: '11.5'
    charset: utf8
    default_table_options:
      charset: utf8

    url: '%env(resolve:DATABASE_URL)%'

    types:
      uuid: 'App\Domain\Model\Game\Entity\UuidType'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Game:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/Model/Game/Entity'
        prefix: 'App\Domain\Model\Game\Entity'
        alias: Game
